name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: Install dependencies
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          gitbook -V
          sudo apt-get update 
          sudo apt-get install -y calibre
      - name: Build
        run: gitbook build
      - name: Build EPUB
        run: gitbook epub
      - name: build pdf    
        run: gitbook pdf
      - name: build mobi
        run: gitbook mobi
      - name: Upload book to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: book EPUB
          path: book.epub
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: book pdf
          path: book.pdf
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: book mobi
          path: book.mobi