name: Build and Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          sudo gitbook -V
      - run: |
          sudo apt-get clean && apt-get update
          sudo apt-get install -y calibre
          gitbook build
        
